### ISSUE TITLE
Euroscope crashes 3.2.1.12 (3.2a(r12))

### ISSUE THREAD

**Issue by ghost** [pierr3/vSMR#25] opened 2016-09-28 08:45 UTC
When I use vSMR Euroscrope crashes from time to time. I've tried various combinations of plug in's and I'm almost certain vSMR is the problem. It seems worse when there is a lot of traffic, but this could just be that an aircraft with a flightplan/scenario with a problem is more likely to appear. 

Is there any logging or anything I can do to help narrow this down? It is very frustrating and I love vSMR! I don't want to remove it.

I don't know C++, but I am a C# developer so if there is any way of attaching to and debugging the process to see what exception if any is raised do let me know.

**Comment by eliuuk** [comment] 2016-10-01 20:06
I'm also having the same issue, it's crashed on me countless times today whilst controlling Munich Delivery (on an event).

**Comment by Koploper9** [comment] 2016-10-16 18:29
Yesterday was the day of Brussels Overload, we all had this problem. It seems to be something serious. I've reïnstalled the beta version.

**Comment by kusterjs** [comment] 2016-10-18 07:58
Any one the same experiences with r10 or previous ES version? Because r12 is pretty buggy anyways, so it might well be only a problem of ES itself.

**Comment by pierr3** [comment] 2016-10-18 11:29
I never got to reproduce the issue myself, although I never tried with r12, but I think (not sure at all) I've had report of the plugin crashing on r10. If someone could test this that'd be great. Can someone who has the problem try to see if it would be in any way related to when RIMCAS would trigger? Meaning when you see two aircrafts on a runway or an aircraft approaching a runway? I'll try to produce a debug build if I have time.

**Comment by ghost** [comment] 2016-10-18 14:33
Pierr, is there any logging I can switch on to catch whatever exception might be thrown? The crash happens regularly for me, I get no error message and don't know what scenario actually makes it happen.

**Comment by eliuuk** [comment] 2016-10-18 17:31
It freezes and crashes for me, that's the most I can say.

**Comment by eliuuk** [comment] 2016-12-26 18:56
@pierr3 Any progress on this issue?

In response to your question, I don't think it's got anything to do with RIMCAS as I was crashing even on Delivery at different times, normally 30 minutes although vSMR crashed ES sometimes 2 minutes after reloading.

**Comment by pierr3** [comment] 2016-12-26 22:45
@indianbhaji I'm sorry but I have not touched vSMR for months, and in fact don't even have the tools installed anymore. Other priorities and interests have taken over and I'm afraid I'm no longer involved in VATSIM in general, hopefully someone with the required skills can have a look and fix this, but I most probably won't be developing vSMR further.

**Comment by eliuuk** [comment] 2016-12-26 22:49
@pierr3 Alright, thanks for your response and good luck with your future
endeavours.

**Comment by pierr3** [comment] 2017-01-29 16:50
I've included a logging system in the nightly build, as well as the debug DLL. Download it here: https://ci.appveyor.com/api/projects/pierr3/vSMR/artifacts/vSMR-nightly.zip

Once loaded into ES, type the command ".smr log" to start logging, a file "vsmr.log" should be created in the same folder as the DLL. If Euroscope crashes, post here any error messages you get and the **last 5 lines** of the log file. I recommend you delete your log file every time you restart EuroScope as it's gonna get big quite fast.

**Comment by Koploper9** [comment] 2017-02-06 18:26
Hello, I've installed the nightly build and here are my findings:

For some reason, I can't create the logging file, I'm running ES in Administrator mode. I can type and enter the command and it seems like it's accepted, yet, no logging file is created. Since this release, ES also has a lag of about 5s when I'm on the ground radar. At last, when I try to close ES and I've opened a ground radar during the session, it always crashes, instead of only every now and then.

No offence to anyone, just my findings.

**Comment by pierr3** [comment] 2017-02-06 18:29
@Koploper9 create an empty text file called vsmr.log in the same folder as the the vSMR dll file, after typing the command the plugin will log into that file, it's a problem with some system where the plugin can write in the file but can't create it. For the lag, it's normal, it's a debug build which is less optimised and will lag a lot of some lower-end systems, if it's not usable on your machine don't worry, we'll debug with someone else. I'll investigate the crash closing, thanks!

**Comment by Koploper9** [comment] 2017-02-07 19:40
@pierr3 Thanks for the reply, I've just tried to create a file in my DLL folder, but it remains completely empty. Nothing is logged. I've also taken a look at the Task Manager while I was running EuroScope, I don't know much about programming, but I think that there shouldn't be lag when I'm only using 32% of my processor and 62% of my memory. Could I be missing a Microsoft Visual C++ Redistributable Package or something like that?

**Comment by pierr3** [comment] 2017-02-27 01:25
@Koploper9 That's weird, please triple check that you're using the new DLL, that there is an empty text file called "vsmr.log" in the same folder as the DLL, and that when you start EuroScope you type in the command ".smr log", don't worry about the performance issues, it's normal.

**Comment by pierr3** [comment] 2017-02-27 01:26
@morphicsphil Could you try to catch the error in the log file?

**Comment by ghost** [comment] 2017-02-27 17:02
@pierr3 yep, I've just downloaded the version listed in this thread and I'll run with logging on from now on to see if I can catch it

**Comment by ghost** [comment] 2017-02-27 17:29
@pierr3 the build I just grabbed makes ES so slow for me that it hangs when I try to switch to an vSMR view

**Comment by pierr3** [comment] 2017-02-28 15:59
@morphicsphil @Koploper9 I've changed the nightly build to Release mode, that should fix the lag problems, if you could try it out again that'd be great. (Same link as before)

**Comment by ghost** [comment] 2017-02-28 21:45
@pierr3  ok

**Comment by Koploper9** [comment] 2017-03-01 20:12
@pierr3 I've found my logging file. For me, it's located somewhere in AppData (don't ask why, I don't know) Since your re-release of the Nightly build, EuroScope doesn't crash anymore when I'm closing the program. Could it be possible that the crash is due to a performance issue? The first time we experienced this was during Brussels overload (high traffic load and ES was run on a laptop instead of a more powerful desktop), and the second time was during the first nightly build, which could also have been due to the not optimised performance. Again, I don't know a lot about these things, just my thoughts, I'll send you the logging when I have another ES crash.

**Comment by pierr3** [comment] 2017-03-02 17:01
@Koploper9 Debug builds are quite dodgy, having moved it to Release might have fixed the problem, I really hope it did, please report back if you experience any more problems.

**Comment by pierr3** [comment] 2017-03-25 15:15
Should be fixed thanks to @LB767 in #29, besides no more crashing reports, I consider this case closed, please drop a message here if it happens again

**Closed as completed by pierr3** 2017-03-25 15:15 UTC
Labels: bug

**Comment by Koploper9** [comment] 2017-04-06 12:46
Hello again, sorry to reopen this issue, but I've tried to use vSMR on my older Vista laptop. EuroScope still crashes when I'm closing an SMR radar. I've managed to save the logging and I've also found the Windows crash report. I've made a ZIP of all these files and I've attached them to this post. It isn't a big problem for me because I don't often use my old laptop and vSMR is working fine on my other computers, but I thought you might find this helpful to fix this problem.
[Euroscope.zip](https://github.com/pierr3/vSMR/files/902537/Euroscope.zip)
